{
  "openapi": "3.0.3",
  "info": {
    "title": "Cube Osmium HTTP API",
    "contact": {
      "name": "Cube",
      "url": "https://www.cube.exchange",
      "email": "support@cube.exchange"
    },
    "version": "0.1.0"
  },
  "paths": {
    "/orders": {
      "get": {
        "parameters": [
          {
            "in": "query",
            "name": "subaccountId",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/TraderId"
            },
            "style": "form"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_OrdersResponse"
                }
              }
            }
          },
          "500": {
            "description": "An error was encountered while processing the request.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_AnyValue",
                  "example": {
                    "error": {
                      "code": "E10000",
                      "reason": "Reason"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "requestBody": {
          "description": "Cancel all resting orders, optionally limiting to a particular market and /\n or order book side.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MassCancelRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_MassCancelResponse"
                }
              }
            }
          },
          "500": {
            "description": "An error was encountered while processing the request.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_AnyValue",
                  "example": {
                    "error": {
                      "code": "E10000",
                      "reason": "Reason"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/order": {
      "post": {
        "requestBody": {
          "description": "Place a new order.\n\n Execution details:\n - For market orders, exactly one of `quantity` or `quote_quantity` must be\n    specified.\n - For MARKET_WITH_PROTECTION, if `price` is specified, it will override the\n    default protection price.\n - Matching will stop upon reaching the protection price, or `quantity` (or\n    `quote_quantity`) filled.\n - When specifying `quote_quantity`, the order is considered 'fully filled'\n    when there is insufficient remaining quote quantity to fill 1 lot at the\n    next trade price. In that case, there will _not_ be a `CancelOrderAck`\n    published.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NewOrderRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_NewOrderResponse"
                }
              }
            }
          },
          "500": {
            "description": "An error was encountered while processing the request.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_AnyValue",
                  "example": {
                    "error": {
                      "code": "E10000",
                      "reason": "Reason"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "requestBody": {
          "description": "Cancel a resting order.\n Note that this can be done before the order is acknowledged (an aggressive\n cancel) since the identifying field is the `client_order_id`.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CancelOrderRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_CancelOrderResponse"
                }
              }
            }
          },
          "500": {
            "description": "An error was encountered while processing the request.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_AnyValue",
                  "example": {
                    "error": {
                      "code": "E10000",
                      "reason": "Reason"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "requestBody": {
          "description": "Modify a resting order.\n - If the `newPrice` and the current resting order's price is the same, and\n `newQuantity` is not greater, then the modify is considered a modify down,\n and the FIFO queue priority is maintained. Otherwise, the modify-order\n request is treated as an atomic cancel-replace and the replacement order is\n placed at the end of the FIFO queue for the new price level.\n - If post-only is specified and the replacement order would trade, then the\n request is rejected and the current resting order remains resting.\n\n Currently, in-flight-mitigation (IFM) is always enabled. That is, the\n cumulative fill qty is subtracted from `newQuantity` to calculate the new\n resting quantity. For example:\n\n ```text\n           | Resting | Filled\n ---------+---------+--------\n New 5    | 5       | 0\n Fill 2   | 3       | 2\n Modify 4 | 2       | 2\n ```\n\n The post-modify quantity will be `newQuantity - filled = 4 - 2 = 2`.\n\n Regardless of IFM, the invariant for order quantity is that `quantity =\n remaining_quantity + cumulative_quantity`.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ModifyOrderRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_ModifyOrderResponse"
                }
              }
            }
          },
          "500": {
            "description": "An error was encountered while processing the request.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_AnyValue",
                  "example": {
                    "error": {
                      "code": "E10000",
                      "reason": "Reason"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/positions": {
      "get": {
        "parameters": [
          {
            "in": "query",
            "name": "subaccountId",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/TraderId"
            },
            "style": "form"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_Array_of_Position"
                }
              }
            }
          },
          "500": {
            "description": "An error was encountered while processing the request.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Body_for_AnyValue",
                  "example": {
                    "error": {
                      "code": "E10000",
                      "reason": "Reason"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiKey": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key",
        "description": "The API Key ID as specified in the [API settings page](https://cube.exchange/settings/api).\n\nEach API key has a corresponding access level that is set when the key is created.\n- Read access only allows access to read HTTP methods (GET, HEAD, etc.).\n- Write access allows access to all HTTP methods.\n"
      },
      "ApiSignature": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-signature",
        "description": "The API signature string authenticating this request.\n\nThe payload to be signed is the concatenation of the byte string `cube.xyz` and the current unix epoch timestamp in seconds converted into an 8-byte little-endian array. The signature is the HMAC-SHA256 digest of the payload using the secret key associated with the specified API key.\n\nImplementation notes:\n- The signature is base-64 encoded with the 'standard' alphabet and\n  padding.\n\n  ```\n  ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\n  ```\n- The timestamp should be encoded as 8-byte little-endian (array of bytes)\n- The secret key should be decoded from a hex string into a 32-byte array of\n  bytes\n"
      },
      "ApiTimestamp": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-timestamp",
        "description": "The timestamp used for signature generation."
      }
    },
    "headers": {
      "x-cube-request-id": {
        "description": "The cube-assigned ID for this request. If known, please supply with support requests",
        "style": "simple",
        "required": true,
        "schema": {
          "title": "RequestId",
          "type": "string",
          "format": "uuid"
        },
        "example": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      }
    },
    "schemas": {
      "TraderId": {
        "type": "integer",
        "format": "uint64",
        "minimum": 0
      },
      "Body_for_OrdersResponse": {
        "type": "object",
        "properties": {
          "result": {
            "$ref": "#/components/schemas/OrdersResponse"
          }
        },
        "required": [
          "result"
        ]
      },
      "OrdersResponse": {
        "type": "object",
        "properties": {
          "orders": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ActiveOrder"
            }
          }
        },
        "required": [
          "orders"
        ],
        "example": {
          "orders": [
            {
              "clientOrderId": 1720791407860,
              "exchangeOrderId": 610000,
              "marketId": 100004,
              "status": 2,
              "price": 656000,
              "stopPrice": null,
              "orderQuantity": 3300,
              "orderQuoteQuantity": null,
              "side": 0,
              "timeInForce": 1,
              "orderType": 0,
              "remainingQuantity": 3300,
              "cumulativeQuantity": 0,
              "restTime": 1720791407909233000,
              "subaccountId": 8,
              "cancelOnDisconnect": false
            },
            {
              "clientOrderId": 1721139361991,
              "exchangeOrderId": 630003,
              "marketId": 100022,
              "status": 2,
              "price": 1560,
              "stopPrice": null,
              "orderQuantity": 1500,
              "orderQuoteQuantity": null,
              "side": 1,
              "timeInForce": 1,
              "orderType": 0,
              "remainingQuantity": 1000,
              "cumulativeQuantity": 500,
              "restTime": 1721139361998122000,
              "subaccountId": 8,
              "cancelOnDisconnect": false
            },
            {
              "clientOrderId": 1770053569827,
              "exchangeOrderId": 630004,
              "marketId": 100022,
              "status": 1,
              "price": null,
              "stopPrice": 1400,
              "orderQuantity": 1500,
              "orderQuoteQuantity": null,
              "side": 1,
              "timeInForce": 1,
              "orderType": 3,
              "remainingQuantity": 1500,
              "cumulativeQuantity": 0,
              "restTime": 1721139361998122000,
              "subaccountId": 8,
              "cancelOnDisconnect": false
            }
          ]
        }
      },
      "ActiveOrder": {
        "description": "An active order. Sent on bootstrap in `ActiveOrders`.\n Might be a resting order or a pending order, depending on the status.",
        "type": "object",
        "properties": {
          "clientOrderId": {
            "description": "The client order ID specified in the new-order request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "exchangeOrderId": {
            "description": "[Exchange order ID](/trade-api.md#exchange-order-id)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "marketId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "status": {
            "description": "Whether the order is resting on the book or pending e.g.",
            "type": "integer",
            "format": "int32"
          },
          "price": {
            "description": "When `status` is OPEN: the resting price of the order.\n When `status` is PENDING_OPEN: the price specified\n on the most recent new-order or modify-order request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "stopPrice": {
            "description": "The stop price specified on the most recent new-order or modify-order request.\n Only present when `order_type` is STOP_LOSS or STOP_LIMIT.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "orderQuantity": {
            "description": "The base quantity submitted in the latest new-order or modify-order request, if any.\n For a PENDING_OPEN order specified in quote quantity,\n that quantity will be converted to Base Quantity at the Stop Price to determine this value.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "orderQuoteQuantity": {
            "description": "The quote quantity submitted in the latest new-order or modify-order request, if any.\n If the order was specified in base quantity, or has rested on the book, this will not be sent.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "side": {
            "type": "integer",
            "format": "int32"
          },
          "timeInForce": {
            "type": "integer",
            "format": "int32"
          },
          "orderType": {
            "type": "integer",
            "format": "int32"
          },
          "remainingQuantity": {
            "description": "The base quantity currently remaining to be filled for this active order.\n when status is PENDING_OPEN, this field will equal to order_quantity.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "cumulativeQuantity": {
            "description": "The base quantity filled thus far for this active order.\n when status is PENDING_OPEN, this field will be 0.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "restTime": {
            "description": "[Transact time](/trade-api.md#transact-time) of the NewOrderAck",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "subaccountId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "cancelOnDisconnect": {
            "description": "If true, this order will be cancelled if the connection that placed it becomes disconnected.",
            "type": "boolean"
          }
        },
        "required": [
          "clientOrderId",
          "exchangeOrderId",
          "marketId",
          "status",
          "orderQuantity",
          "side",
          "timeInForce",
          "orderType",
          "remainingQuantity",
          "cumulativeQuantity",
          "restTime",
          "subaccountId",
          "cancelOnDisconnect"
        ]
      },
      "Body_for_AnyValue": {
        "type": "object",
        "properties": {
          "error": {
            "$ref": "#/components/schemas/ErrorBody_for_AnyValue"
          }
        },
        "required": [
          "error"
        ]
      },
      "ErrorBody_for_AnyValue": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "reason": {
            "type": "string"
          }
        },
        "required": [
          "code",
          "reason"
        ]
      },
      "MassCancelRequest": {
        "description": "Cancel all resting orders, optionally limiting to a particular market and /\n or order book side.",
        "type": "object",
        "properties": {
          "subaccountId": {
            "description": "The subaccount to cancel orders for.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "A request ID that is echoed back on the MassCancelAck and individual\n CancelOrderAck's.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "marketId": {
            "description": "If specified, only orders on the corresponding market will be canceled.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "side": {
            "description": "If specified, only orders with this side will be canceled.",
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "signature": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/SignatureInfo"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "subaccountId",
          "requestId"
        ],
        "example": {
          "subaccountId": 8,
          "requestId": 1721194173903564000,
          "marketId": 100004,
          "side": 0,
          "signature": null
        }
      },
      "SignatureInfo": {
        "type": "object",
        "properties": {
          "timestamp": {
            "description": "Unused",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "verificationKey": {
            "description": "Base-64 encoded `cube_ov_utils::ov_schema::PublicKey`",
            "type": "string"
          },
          "signature": {
            "description": "Base-64 encoded signature of this request",
            "type": "string"
          }
        },
        "required": [
          "timestamp",
          "verificationKey",
          "signature"
        ]
      },
      "Body_for_MassCancelResponse": {
        "type": "object",
        "properties": {
          "result": {
            "$ref": "#/components/schemas/MassCancelResponse"
          }
        },
        "required": [
          "result"
        ]
      },
      "MassCancelResponse": {
        "description": "Mass-cancel-ack confirms a mass-cancel request. If `reason` is set, the mass\n cancel was not applied and there are no affected orders. In addition to this message,\n A separate CancelOrderAck will be sent for each order that was affected.",
        "type": "object",
        "properties": {
          "msgSeqNum": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "subaccountId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "The request ID specified in the mass-cancel request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "transactTime": {
            "description": "[Transact time](/trade-api.md#transact-time)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "reason": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "totalAffectedOrders": {
            "description": "The total number of orders that were canceled.",
            "type": "integer",
            "format": "uint32",
            "minimum": 0
          }
        },
        "required": [
          "msgSeqNum",
          "subaccountId",
          "requestId",
          "transactTime",
          "totalAffectedOrders"
        ],
        "example": {
          "msgSeqNum": 10,
          "subaccountId": 8,
          "requestId": 1721194173903564000,
          "transactTime": 1721564617171865000,
          "reason": null,
          "totalAffectedOrders": 3
        }
      },
      "NewOrderRequest": {
        "description": "Place a new order.\n\n Execution details:\n - For market orders, exactly one of `quantity` or `quote_quantity` must be\n    specified.\n - For MARKET_WITH_PROTECTION, if `price` is specified, it will override the\n    default protection price.\n - Matching will stop upon reaching the protection price, or `quantity` (or\n    `quote_quantity`) filled.\n - When specifying `quote_quantity`, the order is considered 'fully filled'\n    when there is insufficient remaining quote quantity to fill 1 lot at the\n    next trade price. In that case, there will _not_ be a `CancelOrderAck`\n    published.",
        "type": "object",
        "properties": {
          "clientOrderId": {
            "description": "A unique order ID assigned by the client for this order. The ID must be\n unique among open orders by this subaccount.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "A request ID that is echoed back on the NewOrderAck or NewOrderReject",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "marketId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "price": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "quantity": {
            "description": "Required for LIMIT orders.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "side": {
            "type": "integer",
            "format": "int32"
          },
          "timeInForce": {
            "type": "integer",
            "format": "int32"
          },
          "orderType": {
            "type": "integer",
            "format": "int32"
          },
          "subaccountId": {
            "description": "The subaccount to place this order on. This subaccount must be writable by\n the API key specified in the Credentials message.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "selfTradePrevention": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "postOnly": {
            "type": "integer",
            "format": "int32"
          },
          "cancelOnDisconnect": {
            "description": "If true, this order will be automatically cancelled\n after the closure of the network connection\n between Cube's servers and the client that placed the order.\n\n If the client initiates the disconnect or network instability drops the connection,\n the order will be cancelled when Cube's servers recognize the disconnection.\n\n In the event of a server-side disconnect that causes a halt in trading,\n such as scheduled downtime, the order will be cancelled before trading resumes.",
            "type": "boolean"
          },
          "quoteQuantity": {
            "description": "The quantity of the quote asset that the user wants to spend (for a BID) or\n receive (for an ASK). For limit orders, this is immediately converted to a\n base quantity using the provided price. For market orders, this is the\n maximum quantity that will be executed.\n\n Note that lot size rules will be respected, and the actual quantity\n executed will be expressed in base quantity units.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "stopPrice": {
            "description": "The price at which a Stop Order will trigger.  Only valid for STOP_LOSS and STOP_LIMIT.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "signature": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/SignatureInfo"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "clientOrderId",
          "requestId",
          "marketId",
          "side",
          "timeInForce",
          "orderType",
          "subaccountId",
          "postOnly",
          "cancelOnDisconnect"
        ],
        "example": {
          "clientOrderId": 1,
          "requestId": 1,
          "marketId": 300003,
          "price": 21567,
          "quantity": 12345,
          "side": 0,
          "timeInForce": 0,
          "orderType": 0,
          "subaccountId": 3,
          "selfTradePrevention": 0,
          "postOnly": 0,
          "cancelOnDisconnect": false,
          "quoteQuantity": null,
          "stopPrice": null,
          "signature": {
            "timestamp": 0,
            "verificationKey": "EiAtp878L+l7XeqEYucOrDbsdZiljsYQHwXmmBc54Z4Icw",
            "signature": "ZeI82Dv+je6uKM4tGenzFN0pBa1XU7F+bwzqmfD/3PG4xKk7hgRCKb6MddIr61MDQ8wtNpDnJbseFgfPPKimCw"
          }
        }
      },
      "Body_for_NewOrderResponse": {
        "type": "object",
        "properties": {
          "result": {
            "$ref": "#/components/schemas/NewOrderResponse"
          }
        },
        "required": [
          "result"
        ]
      },
      "NewOrderResponse": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "Ack": {
                "$ref": "#/components/schemas/NewOrderAck"
              }
            },
            "required": [
              "Ack"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "Rej": {
                "$ref": "#/components/schemas/NewOrderReject"
              }
            },
            "required": [
              "Rej"
            ],
            "additionalProperties": false
          }
        ],
        "example": {
          "Ack": {
            "msgSeqNum": 10,
            "clientOrderId": 1721188848244274000,
            "requestId": 1721188848288393000,
            "exchangeOrderId": 630005,
            "marketId": 100004,
            "status": 2,
            "price": 656000,
            "stopPrice": null,
            "quantity": 3300,
            "side": 0,
            "timeInForce": 1,
            "orderType": 0,
            "transactTime": 1721193327116302000,
            "subaccountId": 8,
            "cancelOnDisconnect": false,
            "quoteQuantity": null,
            "algoStrategyId": null
          }
        }
      },
      "NewOrderAck": {
        "description": "New-order-ack confirms a new-order request. The ack will be ordered before\n any fills for this order.",
        "type": "object",
        "properties": {
          "msgSeqNum": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "clientOrderId": {
            "description": "The client order ID specified in the new-order request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "The request ID specified in the new-order request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "exchangeOrderId": {
            "description": "[Exchange order ID](/trade-api.md#exchange-order-id)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "marketId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "status": {
            "description": "Whether the order is pending or open after being accepted.\n For Stop orders, this will be PENDING_OPEN.  For other orders, it will be OPEN.\n See comment on similar field in \\[ModifyOrderAck\\].",
            "type": "integer",
            "format": "int32"
          },
          "price": {
            "description": "The price submitted in the new-order request.\n If no price was specified, this will be unset.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "stopPrice": {
            "description": "For Stop Orders, the stop_price specified in the new-order request.\n For other orders, this will be unset.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "quantity": {
            "description": "If `quote_quantity` was not specified, the quantity submitted in the\n new-order request. Otherwise, the quantity of the base asset that was\n executed.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "side": {
            "type": "integer",
            "format": "int32"
          },
          "timeInForce": {
            "type": "integer",
            "format": "int32"
          },
          "orderType": {
            "type": "integer",
            "format": "int32"
          },
          "transactTime": {
            "description": "[Transact time](/trade-api.md#transact-time)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "subaccountId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "cancelOnDisconnect": {
            "type": "boolean"
          },
          "quoteQuantity": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "algoStrategyId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          }
        },
        "required": [
          "msgSeqNum",
          "clientOrderId",
          "requestId",
          "exchangeOrderId",
          "marketId",
          "status",
          "quantity",
          "side",
          "timeInForce",
          "orderType",
          "transactTime",
          "subaccountId",
          "cancelOnDisconnect"
        ]
      },
      "NewOrderReject": {
        "description": "New-order-reject indicates that a new-order request was not applied.",
        "type": "object",
        "properties": {
          "msgSeqNum": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "clientOrderId": {
            "description": "The client order ID specified in the new-order request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "The request ID specified in the new-order request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "transactTime": {
            "description": "[Transact time](/trade-api.md#transact-time)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "subaccountId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "reason": {
            "type": "integer",
            "format": "int32"
          },
          "marketId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "price": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "quantity": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "side": {
            "type": "integer",
            "format": "int32"
          },
          "timeInForce": {
            "type": "integer",
            "format": "int32"
          },
          "orderType": {
            "type": "integer",
            "format": "int32"
          },
          "quoteQuantity": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "algoStrategyId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "stopPrice": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          }
        },
        "required": [
          "msgSeqNum",
          "clientOrderId",
          "requestId",
          "transactTime",
          "subaccountId",
          "reason",
          "marketId",
          "side",
          "timeInForce",
          "orderType"
        ]
      },
      "CancelOrderRequest": {
        "description": "Cancel a resting order.\n Note that this can be done before the order is acknowledged (an aggressive\n cancel) since the identifying field is the `client_order_id`.",
        "type": "object",
        "properties": {
          "marketId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "clientOrderId": {
            "description": "The order ID specified by the client on the NewOrder request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "A request ID that is echoed back on the CancelOrderAck or CancelOrderReject",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "subaccountId": {
            "description": "The subaccount that the NewOrder was placed on.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "signature": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/SignatureInfo"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "marketId",
          "clientOrderId",
          "requestId",
          "subaccountId"
        ],
        "example": {
          "marketId": 100004,
          "clientOrderId": 1721188848244274000,
          "requestId": 1721188848288393000,
          "subaccountId": 8,
          "signature": null
        }
      },
      "Body_for_CancelOrderResponse": {
        "type": "object",
        "properties": {
          "result": {
            "$ref": "#/components/schemas/CancelOrderResponse"
          }
        },
        "required": [
          "result"
        ]
      },
      "CancelOrderResponse": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "Ack": {
                "$ref": "#/components/schemas/CancelOrderAck"
              }
            },
            "required": [
              "Ack"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "Rej": {
                "$ref": "#/components/schemas/CancelOrderReject"
              }
            },
            "required": [
              "Rej"
            ],
            "additionalProperties": false
          }
        ],
        "example": {
          "Ack": {
            "msgSeqNum": 10,
            "clientOrderId": 1721188848244274000,
            "requestId": 1721188848288393000,
            "transactTime": 1721188848329501000,
            "subaccountId": 8,
            "reason": 2,
            "marketId": 100004,
            "exchangeOrderId": 630005,
            "baseQuantityCanceled": 3300
          }
        }
      },
      "CancelOrderAck": {
        "description": "Cancel-order-ack confirms a cancel request, or that an order has been\n canceled as the result of a different user-initiated reason.",
        "type": "object",
        "properties": {
          "msgSeqNum": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "clientOrderId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "If the Reason is `DISCONNECT`, `IOC`, `STP_RESTING`, or `STP_AGGRESSING`,\n this request ID will be `u64::MAX`. Otherwise, it will be the request ID of\n the initiated cancel action. For a mass cancel, each cancel order ack will\n have the MassCancel's request_id.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "transactTime": {
            "description": "[Transact time](/trade-api.md#transact-time)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "subaccountId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "reason": {
            "type": "integer",
            "format": "int32"
          },
          "marketId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "exchangeOrderId": {
            "description": "[Exchange order ID](/trade-api.md#exchange-order-id)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "baseQuantityCanceled": {
            "description": "Base quantity remaining to be filled at the time the order was canceled.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          }
        },
        "required": [
          "msgSeqNum",
          "clientOrderId",
          "requestId",
          "transactTime",
          "subaccountId",
          "reason",
          "marketId",
          "exchangeOrderId",
          "baseQuantityCanceled"
        ]
      },
      "CancelOrderReject": {
        "description": "Cancel-order-reject indicates that a cancel-order request was not applied.",
        "type": "object",
        "properties": {
          "msgSeqNum": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "clientOrderId": {
            "description": "The client order ID specified in the cancel-order request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "The request ID specified in the cancel-order request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "transactTime": {
            "description": "[Transact time](/trade-api.md#transact-time)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "subaccountId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "reason": {
            "type": "integer",
            "format": "int32"
          },
          "marketId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          }
        },
        "required": [
          "msgSeqNum",
          "clientOrderId",
          "requestId",
          "transactTime",
          "subaccountId",
          "reason",
          "marketId"
        ]
      },
      "ModifyOrderRequest": {
        "description": "Modify a resting order.\n - If the `newPrice` and the current resting order's price is the same, and\n `newQuantity` is not greater, then the modify is considered a modify down,\n and the FIFO queue priority is maintained. Otherwise, the modify-order\n request is treated as an atomic cancel-replace and the replacement order is\n placed at the end of the FIFO queue for the new price level.\n - If post-only is specified and the replacement order would trade, then the\n request is rejected and the current resting order remains resting.\n\n Currently, in-flight-mitigation (IFM) is always enabled. That is, the\n cumulative fill qty is subtracted from `newQuantity` to calculate the new\n resting quantity. For example:\n\n ```text\n           | Resting | Filled\n ---------+---------+--------\n New 5    | 5       | 0\n Fill 2   | 3       | 2\n Modify 4 | 2       | 2\n ```\n\n The post-modify quantity will be `newQuantity - filled = 4 - 2 = 2`.\n\n Regardless of IFM, the invariant for order quantity is that `quantity =\n remaining_quantity + cumulative_quantity`.",
        "type": "object",
        "properties": {
          "marketId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "clientOrderId": {
            "description": "The order ID specified by the client on the NewOrder request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "A request ID that is echoed back on the ModifyOrderAck or ModifyOrderReject",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "newPrice": {
            "description": "The updated price for the order.\n Required, unless modifying an untriggered STOP_LOSS order,\n in which case leaving this field unset will remove the protection price,\n following the same semantics as NewOrder.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "newStopPrice": {
            "description": "The price at which a Stop Order will trigger.\n Only valid for untriggered STOP_LOSS and STOP_LIMIT orders.\n If order is a Stop Order and has already triggered,\n this field must not be set.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "newQuantity": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "subaccountId": {
            "description": "The subaccount that the NewOrder was placed on.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "selfTradePrevention": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "postOnly": {
            "type": "integer",
            "format": "int32"
          },
          "signature": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/SignatureInfo"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "marketId",
          "clientOrderId",
          "requestId",
          "newQuantity",
          "subaccountId",
          "postOnly"
        ],
        "example": {
          "marketId": 100004,
          "clientOrderId": 1721212575078893000,
          "requestId": 1721212575263679000,
          "newPrice": 656000,
          "newStopPrice": null,
          "newQuantity": 3300,
          "subaccountId": 8,
          "selfTradePrevention": 1,
          "postOnly": 0,
          "signature": null
        }
      },
      "Body_for_ModifyOrderResponse": {
        "type": "object",
        "properties": {
          "result": {
            "$ref": "#/components/schemas/ModifyOrderResponse"
          }
        },
        "required": [
          "result"
        ]
      },
      "ModifyOrderResponse": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "Ack": {
                "$ref": "#/components/schemas/ModifyOrderAck"
              }
            },
            "required": [
              "Ack"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "Rej": {
                "$ref": "#/components/schemas/ModifyOrderReject"
              }
            },
            "required": [
              "Rej"
            ],
            "additionalProperties": false
          }
        ],
        "example": {
          "Ack": {
            "msgSeqNum": 21,
            "clientOrderId": 1721212575078893000,
            "requestId": 1721212575263679000,
            "transactTime": 1721212575309118000,
            "status": 2,
            "remainingQuantity": 3300,
            "subaccountId": 8,
            "marketId": 100004,
            "price": 656000,
            "stopPrice": null,
            "quantity": 3300,
            "cumulativeQuantity": 0,
            "exchangeOrderId": 630009
          }
        }
      },
      "ModifyOrderAck": {
        "description": "Modify-order-ack confirms a modify-order request. If the modify resulted in\n an aggressing cancel-replace, the ack will be ordered before any fills for\n this order.",
        "type": "object",
        "properties": {
          "msgSeqNum": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "clientOrderId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "The request ID specified in the modify request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "transactTime": {
            "description": "[Transact time](/trade-api.md#transact-time)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "status": {
            "description": "Whether the order is pending or open after applying the modify request.\n When a Stop Order triggers, you will receive an unsolicited ModifyOrderAck\n with the status set to `OPEN`.",
            "type": "integer",
            "format": "int32"
          },
          "remainingQuantity": {
            "description": "The quantity remaining on the book after applying the modify request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "subaccountId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "marketId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "price": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "stopPrice": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0,
            "nullable": true
          },
          "quantity": {
            "description": "The quantity submitted in the modify request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "cumulativeQuantity": {
            "description": "The cumulative filled quantity for this order.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "exchangeOrderId": {
            "description": "[Exchange order ID](/trade-api.md#exchange-order-id)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          }
        },
        "required": [
          "msgSeqNum",
          "clientOrderId",
          "requestId",
          "transactTime",
          "status",
          "remainingQuantity",
          "subaccountId",
          "marketId",
          "quantity",
          "cumulativeQuantity",
          "exchangeOrderId"
        ]
      },
      "ModifyOrderReject": {
        "description": "Modify-order-reject indicates that a modify-order request was not applied.",
        "type": "object",
        "properties": {
          "msgSeqNum": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "clientOrderId": {
            "description": "The client order ID specified in the modify-order request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "requestId": {
            "description": "The request ID specified in the modify-order request.",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "transactTime": {
            "description": "[Transact time](/trade-api.md#transact-time)",
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "subaccountId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "reason": {
            "type": "integer",
            "format": "int32"
          },
          "marketId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          }
        },
        "required": [
          "msgSeqNum",
          "clientOrderId",
          "requestId",
          "transactTime",
          "subaccountId",
          "reason",
          "marketId"
        ]
      },
      "Body_for_Array_of_Position": {
        "type": "object",
        "properties": {
          "result": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Position"
            }
          }
        },
        "required": [
          "result"
        ]
      },
      "Position": {
        "anyOf": [
          {
            "$ref": "#/components/schemas/AssetPosition"
          },
          {
            "$ref": "#/components/schemas/ContractPosition"
          }
        ]
      },
      "AssetPosition": {
        "type": "object",
        "properties": {
          "assetId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "total": {
            "type": "string",
            "format": "number"
          },
          "available": {
            "type": "string",
            "format": "number"
          }
        },
        "required": [
          "assetId",
          "total",
          "available"
        ],
        "example": {
          "assetId": 100004,
          "total": "13050000",
          "available": "12780000"
        }
      },
      "ContractPosition": {
        "type": "object",
        "properties": {
          "contractId": {
            "type": "integer",
            "format": "uint64",
            "minimum": 0
          },
          "netContractUnits": {
            "type": "integer",
            "format": "int64"
          },
          "quote": {
            "type": "string",
            "format": "number"
          },
          "bids": {
            "type": "string",
            "format": "number"
          },
          "asks": {
            "type": "string",
            "format": "number"
          },
          "leverage": {
            "description": "Leverage override for this contract, if any",
            "type": "integer",
            "format": "uint16",
            "minimum": 1,
            "maximum": 65535,
            "nullable": true
          }
        },
        "required": [
          "contractId",
          "netContractUnits",
          "quote",
          "bids",
          "asks"
        ],
        "example": {
          "contractId": 100004,
          "netContractUnits": 100,
          "quote": "-1.0",
          "bids": "0",
          "asks": "0"
        }
      }
    }
  }
}